### ISSUE TITLE
Multiple Corporation, or alliance support

### ISSUE THREAD

**Issue by TrentBartlem** [DavidBurela/DustTimers#1]
As a user
I want to view the timers for multiple corporations at the same time
So that I get a clearer picture of what's going on.

e.g. something like http://dusttimers.com/WRRVN,DJIN,TSOLE 

Ideally, I'd like to just input the alliance name instead, but I'll settle for this.

**Comment by DavidBurela** [comment]
Yes I totally agree with this. I was planning on implementing this but got distracted with real life.

I plan on implementing it via alliance tickers, the same as how it currently works for corp tickers
e.g. http://DustTimers.com/<Alliance>

**Comment by TrentBartlem** [comment]
Cool

**Comment by DavidBurela** [comment]
Yeah... 12 months later and I still haven't done it.
But hey, I managed to update all the Nuget packages & add application insights to it today. So I can at least make sure the site is up.
